anno_tool/anno/urls.py
#!/usr/bin/env python3
from django.urls import path

from . import views

app_name = 'anno'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:video_id>/<int:start_step>', views.anno, name='anno'),
    path('<int:video_id>/navigate', views.navigate, name='navigate'),
    path('<int:video_id>/edit', views.edit, name='edit'),
    path('<str:setting>/<str:phase>/<int:qa_id>/dataset', views.dataset, name='dataset'),
    path('start/', views.start, name='start'),
    path('resume/', views.resume, name='resume'),
    path('help/', views.help, name='help'),
]
# vim: ts=4 sw=4 sts=4 expandtab

anno_tool/anno_tool/urls.py
from django.contrib import admin
from django.urls import path, include
from anno_tool import views

urlpatterns = [
    path('', views.index, name='index'),
    path('anno/', include('anno.urls')),
    path('humantest/', include('humantest.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name="signup"),
    path('admin/', admin.site.urls),
]

anno_tool/anno/models.py
from django.db import models


class Video(models.Model):
    video_name = models.CharField(max_length=200, default="")
    video_class = models.CharField(max_length=200, default="")
    # cut points, seprated by comma. e.g. 1,3,5,10
    cut_points = models.CharField(max_length=200, default="")
    """state of the video
    0: not annotated
    1: annotating
    2: finished
    """
    STATE_CHOICES = [
        (0, 'NOT ANNOTATED'),
        (1, 'ANNOTATING'),
        (2, 'FINISHED'),
    ]

    CERTAINTY_CHOICES = [
        (0, 'UNCERTAIN'),
        (1, 'CERTAIN'),
    ]

    state = models.PositiveSmallIntegerField(default=0, choices=STATE_CHOICES)
    certainty = models.BooleanField(default=True, choices=CERTAINTY_CHOICES)
    note = models.CharField(max_length=300, default="")

    checkpoint = models.PositiveSmallIntegerField(default=0)

    # total steps
    steps = models.PositiveSmallIntegerField(default=0)

    train = models.BooleanField(default=True)

    action_ids = models.CharField(max_length=300, default="")

    prev_vid = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.video_name
# Create your models here.

anno_tool/anno/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Video
import glob
import os
import numpy as np
import json
from .utils import load_action_dict, parse_cuts

INF = 65536

action_dict = load_action_dict()
last_video_id = None
action_names = None

def index(request):
    return render(request, 'anno/index.html', {})


def anno(request, video_id, start_step):
    if video_id == INF:
        return HttpResponse("Congratulations! We have finished!")


    video_id = np.clip(video_id, 1, Video.objects.count())
    video = Video.objects.get(id=video_id)

    if start_step == 99:
        start_step = video.checkpoint
        return HttpResponseRedirect('../{}/{}'.format(video_id, video.checkpoint))

    start_step = np.clip(start_step, 0, video.steps - 1)
    video.checkpoint = start_step
    video.save()

    first_img = sorted(glob.glob('/opt/data5/COIN_COIN/{}/{}/img*.jpg'.format(
        video.video_name,
        start_step
    )))[-1]

    first_img = '/'.join(first_img.split('/')[-3:])

    if start_step < video.steps - 1:
        second_img = sorted(glob.glob('/opt/data5/COIN_COIN/{}/{}/img*.jpg'.format(
            video.video_name,
            start_step + 1
        )))[0]
        second_img = '/'.join(second_img.split('/')[-3:])
    else:
        second_img = None

    # prepare action names
    global last_video_id
    global action_names
    if last_video_id != video_id:
        action_ids = video.action_ids.split(',')
        action_names = [action_dict.get(int(i), '---missing name---') for i in action_ids]
        last_video_id = video_id

    cut_points, clips = parse_cuts(video)

    num_videos = len(Video.objects.all())
    num_finished = len(Video.objects.filter(state=2))
    ratio_finished = (num_finished * 100) // num_videos

    context = {
        "first_img": first_img,
        "first_name": action_names[start_step],
        "second_name": action_names[start_step + 1] if second_img is not None else None,
        "second_img": second_img,
        "video": video,
        "state": Video.STATE_CHOICES[video.state][1],
        "action_names": action_names,
        "start_step": start_step,
        "clip_info": str(clips),
        "cut_points": cut_points,
        "num_videos": num_videos,
        "num_finished": num_finished,
        "ratio_finished": ratio_finished,
    }
    return render(request, 'anno/anno.html', context)

def edit(request, video_id):
    video = get_object_or_404(Video, pk=video_id)
    print(request.POST.keys())
    if "edit" in request.POST:
        post = request.POST["edit"]
        cuts = video.cut_points.split(',')
        cuts = [int(cut) for cut in cuts if cut != '']

        if post == "cut":
            if video.checkpoint != video.steps - 1:
                if video.checkpoint not in cuts:
                    cuts.append(video.checkpoint)
                cuts = sorted(cuts)
                video.cut_points = ','.join([str(cut) for cut in cuts])

                video.state = 1 # annotating
                video.save()
            return HttpResponseRedirect('../{}/{}'.format(video_id, video.checkpoint))
        else:
            deleted_cut = int(post)
            if deleted_cut == -1: # delete all
                video.cut_points = ""
            else:
                cuts.pop(deleted_cut)
                video.cut_points = ",".join(map(str, cuts))
            video.save()
            return HttpResponseRedirect('../{}/{}'.format(video_id, video.checkpoint))
    else:
        video.certainty = not video.certainty
        video.save()
        return HttpResponseRedirect('../{}/{}'.format(video_id, video.checkpoint))

def navigate(request, video_id):
    # navigate in actions and videos
    video = get_object_or_404(Video, pk=video_id)
    post = request.POST["submit"]
    print(request.POST)

    if post == "pv": # previous video
        video = Video.objects.get(pk=video.prev_vid)
        return HttpResponseRedirect('../{}/{}'.format(video.id, video.checkpoint))

    elif post == "nv":# next video
        try:
            video.note = request.POST["comments"]
        except:
            pass
        video.state = 2 # finished
        video.save()
        unfinished_videos = Video.objects.filter(state=0)
        try:
            video = unfinished_videos[0]
            video.prev_vid = video_id
            video.save()
            video_id = video.id
            start_step = video.checkpoint
        except:
            video_id = INF
            start_step = 0
        return HttpResponseRedirect('../{}/{}'.format(video_id, start_step))
    elif post == "na": # next action
        # next action
        video.checkpoint += 1
        video.checkpoint = min(video.steps - 1, video.checkpoint)
        video.state = 1 # annotating
        video.save()
        return HttpResponseRedirect('../{}/{}'.format(video_id, video.checkpoint))

    elif post == "pa": # previous action
        # next action
        video.checkpoint = max(0, video.checkpoint - 1)
        video.state = 1 # annotating
        video.save()
        return HttpResponseRedirect('../{}/{}'.format(video_id, video.checkpoint))

def resume(request):
    unfinished_videos = Video.objects.filter(state=0)
    annotating_videos = Video.objects.filter(state=1)
    try:
        if len(annotating_videos) > 0:
            video = annotating_videos[0]
        else:
            video = unfinished_videos[0]
        start_step = video.checkpoint
        return HttpResponseRedirect('../{}/{}'.format(video.id, video.checkpoint))
    except IndexError:
        return HttpResponseRedirect('../{}/0'.format(INF))

def start(request):
    # start new annotation
    try:
        post = request.POST.get("submit", "continue")
        if post == "resume":
            return resume(request)
        else:
            unfinished_videos = Video.objects.filter(state=0)
            video = unfinished_videos[0]
        return HttpResponseRedirect('../{}/{}'.format(video.id, video.checkpoint))
    except IndexError:
        return HttpResponseRedirect('../{}/0'.format(INF))

def help(request):
    return render(request, "anno/help.html")

metadata = {}
def dataset(request, setting, phase, qa_id):
    assert setting in ['long', 'short', 'long_uniform']
    assert phase in ['train', 'test']
    key = f'{setting}/{phase}'

    if key not in metadata:
        metadata[key] = json.load(open(f'static/metadata/{key}.json', 'r'))

    qa_id = np.clip(qa_id, 0, len(metadata[key]))
    qa = metadata[key][qa_id].copy()
    qa.update({
        "id": qa_id,
        "phase": phase,
        "setting": setting,
    })
    for c in qa['choices']:
        c['gifs'] = [f'{s}/action.gif' for s in c['steps']]

    return render(request, "anno/dataset.html", qa)

# Create your views here.

anno_tool/anno/templates/anno/anno.html
{% extends "anno/base.html" %}
{% load static %}

{% block title %}
  COIN COIN Annotation Tool
{% endblock %}

{% block misc %}
  <link rel="stylesheet" href="{% static 'css/anno.css' %} ">
  <script>
    var init = function () {
      //get scroll position in session storage

      var list_group = $("#action_name_list");
      var height = 0;
      for (let i = 0; i < {{start_step}}; i++) {
        let item = $("#action" + (i+1).toString());
        height += item.outerHeight() - 1;
      }
      list_group.scrollTop(height - 200);
    };
window.onload = init;

$(window).keydown(function(e) {
  switch (e.keyCode) {
    case 67: // C
      $("#cut").click();
      break;
    case 65: // A
      $("#na").click();
      break;
    case 86: // V
      $("#nv").click();
      break;
    case 83: // S
      $("#pa").click();
      break;
    case 66: // B
      $("#pv").click();
      break
    case 37: // left arrow
      document.getElementById('prev_vid').click();
      break;
    case 39: // right arrow
      document.getElementById('next_vid').click();
      break;
    case 13: // enter
      if ($("#vid").is(":focus")){

        var new_vid = $("#vid").val();
        if ("{{video.id}}" != new_vid)
          window.location.replace("/anno/" + $("#vid").val() + "/99");
      }
      e.preventDefault();
      return false;
    case 69: //E end
      window.location.replace("/anno/{{ video.id }}/{{ video.steps|add:"-1"}}");
      break;
    case 70: //F first
      window.location.replace("/anno/{{ video.id }}/0");
      break;
    case 82: //R resume
      window.location.replace("/anno/resume");
      break;
    default:
      if ((!$("#vid").is(":focus"))){
        if (e.keyCode >= 48 && e.keyCode <= 58) {
          // 0 ~ 9
          var target = e.keyCode - 48;
          window.location.replace("/anno/{{ video.id }}/" + target.toString());
        }
      }
      break;
      return false;
  }
});

  </script>

  <style type="text/css" media="screen">
#vid {
  width: 80px;
  text-align: center;
}

.fa-arrows {
  color: #aaa;
  height: 100%;
  width: 1rem;
}

.fa-arrows:hover {
  color: #222;
}

input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance:textfield;
}

/* Bootstrap Toggle v2.2.2 corrections for Bootsrtap 4*/
.toggle-off {
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, .125);
}
.toggle.off {
  border-color: rgba(0, 0, 0, .25);
}

.toggle-handle {
  background-color: white;
  border: thin rgba(0, 0, 0, .25) solid;
}
  </style>

{% endblock %}

{% block navtab %}
  "anno"
{% endblock %}

{% block content %}
  <div class="container-fluid bg-1 text-center" id="main">

    <div class="row" id="toprow">
      <div class="col-sm-3">
        <h4>video id<br/>
          <div class="vid-group">
            <a href="{% url 'anno:anno' video.id|add:"-1" 99 %}" id="prev_vid">
              <span class="fas fa-caret-left fa-arrows"></span>
            </a>
            <small>
              <input type="number" value="{{video.id}}" name="" id="vid" min="1" max="{{ num_videos }}"/>
            </small>
            <a href="{% url 'anno:anno' video.id|add:"1" 99 %}" id="next_vid">
              <span class="fas fa-caret-right fa-arrows"></span>
            </a>
          </div>
        </h4>
      </div>
      <div class="col-sm-3">
        <h4>video name<br/>
          <small>{{ video.video_name }}</small>
        </h4>
      </div>
      <div class="col-sm-3">
        <h4>video class<br/>
          <small>{{ video.video_class }}</small>
        </h4>
      </div>
      <div class="col-sm-3">
        <h4>video state<br/>
          <small>{{ state }}</small>
        </h4>
      </div>
    </div>

    <div class="progress m-3">
      <div class="progress-bar" role="progressbar" style="width: {{ratio_finished}}%;" aria-valuemin="0" aria-valuemax="100">{{num_finished}} / {{num_videos}}</div>
    </div>

    <div class="row">
      <div class="col-sm-3" id="action_names">
        <h4>Action names<br/>
          <small>total steps: {{video.steps}}</small>
        </h4>
        <ol class="list-group" id="action_name_list">
          {% for name in action_names %}
            <a id="action{{forloop.counter}}" class="list-group-item {% if start_step|add:1 == forloop.counter %}active{% endif %}" href="{% url 'anno:anno' video.id forloop.counter|add:"-1" %}">{{ forloop.counter|add:"-1" }}. {{ name }}</a>
          {% endfor %}
        </ol>
      </div>
      <div class="col-sm-9">
        <div class="row">
          <div class="col-sm-6">
            <div style="margin:10px">{{clip_info}}</div>
          </div>
          <div class="col-sm-6">
            <form action="{% url 'anno:edit' video.id %}" method="post">
              {% csrf_token %}
              <button class="btn btn-success btn-edit" type="submit" name="edit", value="cut" id="cut">
                Cut
              </button>
              <div class="btn-group">
                <button type="button" class="btn {{cut_points|yesno:"btn-danger,btn-secondary"}} dropdown-toggle btn-edit disable" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Delete
                </button>
                {% if cut_points %}
                  <div class="dropdown-menu">
                    {% for point in cut_points %}
                      <button class="dropdown-item" href="#" name="edit" value="{{forloop.counter|add:"-1"}}">{{point}}</button>
                    {% endfor %}
                    <div class="dropdown-divider"></div>
                    <button class="dropdown-item" href="#" name="edit" value="-1">All</button>
                  </div>
                {% endif %}
              </div>
              <input type="checkbox" {% if video.certainty %} checked {% endif %} data-toggle="toggle" data-on="Certain" data-off="Uncertain" name="certain" value="1" onchange="this.form.submit()">
            </form>
          </div>
        </div>
        <hr/>
        <form action="{% url 'anno:navigate' video.id %}" method="post">
          {% csrf_token %}
          <button class="btn btn-info btn-nav" type="submit" name="submit" value="pv" id="pv">
            Previous video
          </button>
          {% if start_step > 0 %}
            <button class="btn btn-primary btn-nav" type="submit" name="submit" value="pa" id="pa">
              Previous action
            </button>
          {% endif %}

          {% if start_step|add:1 < video.steps %}
            <button class="btn btn-primary btn-nav" type="submit" name="submit" value="na" id="na">
              Next action
            </button>

          {% endif %}
          <button class="btn btn-info btn-nav" type="submit" name="submit" value="nv" id="nv">
            Next video
          </button>

          <div class="row {% if start_step in cut_points %}border-between{% endif %}" id="images">
          <div class="col-sm-{% if second_img %}6{% else %}12{% endif %}" align="center">
            {% with 'data/'|add:first_img as first_static%}
              <img src="{% static first_static %}" class="img-fluid">
            {% endwith %}
            <h5 class="img-caption">{{ start_step}}: {{ first_name }}</h5>
          </div>
          {% if second_img %}
            <div class="col-sm-6" align="center">
              {% with 'data/'|add:second_img as second_static%}
                <img src="{% static second_static %}" class="img-fluid">
              {% endwith %}
              <h5 class="img-caption">{{ start_step|add:"1"}}: {{ second_name }}</h5>
            </div>
          {% endif %}
          </div>
          {% if not video.certainty %}
            <div class="input-group mb-3">
              <input type="text" id="comments" class="form-control" aria-label="Amount (to the nearest dollar)" placeholder="Input your comments" name="comments" value="{{video.note}}">
            </div>
          {% endif %}
        </form>

      </div>
    </div>
  </div>
{% endblock %}

<!--vim: shiftwidth=2-->

anno_tool/anno/templates/anno/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}Base Site{% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--jquery and popper-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<!--bootstrap css-->
<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!--bootstrap js-->
<script src="{% static "bootstrap/js/bootstrap.min.js" %}" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!--bootstrap-toggle-->
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

<!--fontawesome-->
<!--<script src="https://kit.fontawesome.com/5fcc70e993.js" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<link href="{% static "fontawesome/css/all.css" %}" rel="stylesheet">

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>

{% block misc %}
{% endblock %}

<script>
$(document).ready(function() {
// get current URL path and assign 'active' class
	var id = {% block navtab %} "anno" {% endblock %};
	$("#" + id).addClass('active');
})
</script>

<style>
.fa-icon {
color: #eeeeee;
margin-right: 10px;
font-size:17px;
}

html, body {
	height: 100%;
}

body {
	display: flex;
	flex-direction: column;
}

.container-fluid#main {
	flex: 1 0 auto;
}

footer {
  width: 100%;
  background: #222;
  color: #eee;
  flex-shrink: 0;
  text-align: center;
}

</style>

</head>


<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
	<a class="navbar-brand" href="#">COIN<sup>2</sup></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
		  <a class="nav-link" href="{% url "index" %}" id="home">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="/admin" id="admin">Admin</a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="{% url "anno:start" %}" id="anno">Annotate</a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="{% url "anno:help" %}" id="help">Help</a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="{% url "anno:dataset" setting="long" phase="train" qa_id=0 %}" id="dataset">Dataset</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

<!-- Footer -->
<footer class="footer font-small py-3">

	<div class="container-fluid text-center">
		<div class="row">
			<div class="col-sm-3">
					<i class="fa fa-phone-alt fa-icon" aria-hidden="true"></i><a href="tel:13051108800">13051108800</a>
			</div>
			<div class="col-sm-6">
				Copyright &copy; 2019 <a href="http://ivg.au.tsinghua.edu.cn" target="_blank" style="margin-left: 10px">Tsinghua i-VisionGroup</a>
			</div>
			<div class="col-sm-3">
					<i class="fa fa-envelope-square fa-icon" aria-hidden="true"></i><a href="mailto:zhaowl16@mails.tsinghua.edu.cn?subject=Email Subject line">Email Us</a>
			</div>
		</div>
	</div>
</footer>
</body>
</html>

anno_tool/anno/templates/anno/dataset.html
{% extends "anno/base.html" %}
{% load static %}

{% block title %}
  COIN COIN Annotation Tool
{% endblock %}

{% block misc %}
<style type="text/css" media="screen">
.question {
	width: 30%;
}

.choices {
	width: 15%;
}


#main {
	margin-top: 80px;
	padding-left: 5%;
	padding-right: 5%;
}
</style>
{% endblock %}

{% block navtab %}
  "dataset"
{% endblock %}

{% block content %}
  <div class="container-fluid bg-1" id="main">
	  <div class="row">
		  <div class="col-sm-1">
			  <h5>Question:</h5>
		  </div>
		 <div class="col-sm-5">
		  {% for q in question %}
			  {% with 'data/'|add:q as static_q%}
				  <img src="{% static static_q %}" class="img-fluid question">
			  {% endwith %}
		  {%endfor%}
		</div>
		<div class="col-sm-6">
			{% if id > 0 %}
			<a class="btn btn-primary btn-nav" href="{% url "anno:dataset" setting phase id|add:"-1" %}">
            Prev QA
			{% endif %}
          </a>
			<a class="btn btn-info btn-nav" href="{% url "anno:dataset" setting phase id|add:"1" %}">
            Next QA
          </a>
		  <div class="btn-group">
			<button type="button" class="btn btn-info dropdown-toggle btn-edit disable" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Setting
			</button>
			  <div class="dropdown-menu">
				<a class="dropdown-item" href="{% url "anno:dataset" "long" phase id %}">long</a>
				<a class="dropdown-item" href="{% url "anno:dataset" "long_uniform" phase id %}">long_uniform</a>
				<a class="dropdown-item" href="{% url "anno:dataset" "short" phase id %}">short</a>
			  </div>
		  </div>
		  <div class="btn-group">
			<button type="button" class="btn btn-info dropdown-toggle btn-edit disable" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				Phase
			</button>
			  <div class="dropdown-menu">
				<a class="dropdown-item" href="{% url "anno:dataset" setting "train" id %}">train</a>
				<a class="dropdown-item" href="{% url "anno:dataset" setting "test" id %}">test</a>
			  </div>
		  </div>
		</div>
	  </div>
	  <hr>
	  <h5>Choices:</h5>
	  <ul>
		  {% for c in choices %}
			  <li>
				  <div class="row">
					  <div class="col-sm-11">
				  {% for s in c|get_item:"gifs" %}
					  {% with 'data/'|add:s as static_s%}
						  <img src="{% static static_s %}" class="img-fluid step choices">
					  {% endwith %}
				  {% endfor %}
					  </div>
					  <div class="col-sm-1">
			  <span class="wrong_type" style="color: {% if c|get_item:"correct" %} green {% else %} red {% endif %}">{{c|get_item:"wrong_type"}}</span>
					  </div>
				  </div>
			  </li>
		  {% endfor %}
	  </ul>
	  </div>

  </div>
{% endblock %}

<!--vim: shiftwidth=2-->

anno_tool/anno/templates/anno/index.html
{% extends "anno/base.html" %}
{% block title %}
COIN COIN annotation tool
{% endblock %}

{% block misc %}
<style>
  .container-fluid#main {
  margin-top: 20%;
  line-height: 150px;
}
  .btn-primary{
	  width: 150px;
	  margin: 10px;
  }
</style>
{% endblock %}

{% block navtab %}
	"home"
{% endblock %}

{% block content %}

<div class="container-fluid bg-1 text-center" id="main">
<h1>COIN COIN annotation tool</h1>

<form action="{% url 'anno:start' %}" method="post">
{% csrf_token %}
<button class="btn btn-primary" type="submit" name="submit", value="resume">
	Continue
</button>
<button class="btn btn-primary" type="submit" name="submit", value="new">
	Start new
</button>
</form>
</div>
{% endblock %}