anno_tool/anno/urls.py
#!/usr/bin/env python3
from django.urls import path

from . import views

app_name = 'anno'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:video_id>/<int:start_step>', views.anno, name='anno'),
    path('<int:video_id>/navigate', views.navigate, name='navigate'),
    path('<int:video_id>/edit', views.edit, name='edit'),
    path('<str:setting>/<str:phase>/<int:qa_id>/dataset', views.dataset, name='dataset'),
    path('start/', views.start, name='start'),
    path('resume/', views.resume, name='resume'),
    path('help/', views.help, name='help'),
]
# vim: ts=4 sw=4 sts=4 expandtab

anno_tool/anno_tool/urls.py
from django.contrib import admin
from django.urls import path, include
from anno_tool import views

urlpatterns = [
    path('', views.index, name='index'),
    path('anno/', include('anno.urls')),
    path('humantest/', include('humantest.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name="signup"),
    path('admin/', admin.site.urls),
]

anno_tool/humantest/urls.py
#!/usr/bin/env python3
from django.urls import path

from . import views

app_name = 'humantest'

urlpatterns = [
    path('', views.start, name='index'),
    path('<str:setting>/<str:phase>/start', views.start, name='start'),
    path('stat/', views.stat, name='stat'),
    path('start/', views.start, name='start'),
    path('help/', views.help, name='help'),
    path('<int:qa_id>', views.qa, name='qa'),
    path('<int:qa_id>/choose', views.choose, name='choose'),
]
# vim: ts=4 sw=4 sts=4 expandtab

anno_tool/humantest/models.py
from django.db import models

LENGTH = 30
MAX_USERS = 20
USERNAME_LENGTH = 16

class QA(models.Model):
    """questions
    [start_frame, end_frame]
    """
    question = models.CharField(max_length=2 * LENGTH)
    choices = models.CharField(max_length=LENGTH * 6 * 4)
    """answers from users"""
    answers = models.CharField(max_length=MAX_USERS, default='')
    answerers = models.CharField(max_length=MAX_USERS * USERNAME_LENGTH)
    correct_answer = models.PositiveSmallIntegerField(default=5)

    phase = models.CharField(default='test', max_length=10)
    setting = models.CharField(max_length=20, default='')
 #
# Create your models here.

anno_tool/humantest/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import get_user

import json
import glob
import os

from .models import QA
def index(request):
    return HttpResponseRedirect("/humantest/start")

NUM_QAS = len(QA.objects.all())
NUM_FINISHED = 0

SETTINGS = ['short1', 'long6']
print(SETTINGS)

@login_required(login_url='/accounts/login/')
def help(request):
    return render(request, "humantest/help.html")

@login_required(login_url='/accounts/login/')
def start(request, setting='', phase='test'):
    print(request.COOKIES)
    if setting == '':
        if 'qa_id' in request.COOKIES:
            qa_id = request.COOKIES['qa_id']
            setting = QA.objects.get(pk=qa_id).setting
        else:
            setting = 'long5'
    print(setting)
    # find not answered question
    user = get_user(request)
    selected = QA.objects.filter(setting=setting, phase=phase)
    unanswered_qa = selected.filter(answers='')
    if len(unanswered_qa) == 0:
        unanswered_qa = selected.exclude(answerers__contains=user.username)
    global NUM_FINISHED
    global NUM_QAS
    NUM_QAS = len(selected)
    NUM_FINISHED = NUM_QAS - len(unanswered_qa)
    if len(unanswered_qa) > 0:
        qa = unanswered_qa[0]
        return HttpResponseRedirect(f'/humantest/{qa.id}')
    else:
        return HttpResponse('finished!')

@login_required(login_url='/accounts/login/')
def qa(request, qa_id):
    qa = QA.objects.get(pk=qa_id)
    context = {
        'id': qa_id,
        'question': json.loads(qa.question),
        'choices': json.loads(qa.choices),
        'phase': qa.phase,
        'setting': qa.setting,
        'ratio_finished': NUM_FINISHED * 100 // NUM_QAS,
        'num_finished': NUM_FINISHED,
        'num_qas': NUM_QAS,
        'settings': SETTINGS,
    }
    for c in context['choices']:
        c['gifs'] = [f'{s}/action.gif' for s in c['steps']]

    response = render(request, "humantest/qa.html", context)
    response.set_cookie('qa_id', qa_id)
    return response

@login_required(login_url='/accounts/login/')
def choose(request, qa_id):
    qa = QA.objects.get(pk=qa_id)
    try:
        ans = request.POST["answer"]
        user = get_user(request)
        if qa.answers == '':
            qa.answers = ans
            qa.answerers = user.username
            qa.save()
        else:
            qa.answers += str(ans)
            qa.answerers += f',{user.username}'
            qa.save()
        return HttpResponseRedirect(f'../{qa.setting}/{qa.phase}/start')
    except KeyError:
        return HttpResponseRedirect(f'../{qa_id}')

@login_required(login_url='/accounts/login/')
def stat(request):
    user = get_user(request)
    # qas = QA.objects.filter(answerers__contains=user.username)
    username = user.username
    qas = QA.objects.exclude(answers='').exclude(answerers='tys')

    correct = {}
    num_answered = {}
    all_correct = {}
    all_num_answered = {}

    for qa in qas:
        key = f'{qa.setting}/{qa.phase}'
        ans = int(qa.answers)
        if key in all_num_answered:
            all_num_answered[key] += 1
        else:
            all_num_answered[key] = 1
            all_correct[key] = 0
        if qa.correct_answer == ans:
            all_correct[key] += 1

        if username in qa.answerers:
            index = qa.answerers.split(',').index(username)
            ans = int(qa.answers[index])
            if key in num_answered:
                num_answered[key] += 1
            else:
                num_answered[key] = 1
                correct[key] = 0
            if qa.correct_answer == ans:
                correct[key] += 1

    acc = {
        k: '{:.2f}%'.format(correct[k] * 100 / num_answered[k])
        if num_answered[k] > 0 else '/'
        for k in num_answered.keys()
    }

    all_acc = {
        k: '{:.2f}%'.format(all_correct[k] * 100 / all_num_answered[k])
        if all_num_answered[k] > 0 else '/'
        for k in all_num_answered.keys()
    }

    context = {
        'correct': sorted(correct.items()),
        'num_answered': num_answered,
        'acc': acc,
        'all_correct': sorted(all_correct.items()),
        'all_num_answered': all_num_answered,
        'all_acc': all_acc,
    }
    return render(request, "humantest/stat.html", context)

# Create your views here.

anno_tool/humantest/templates/humantest/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}Base Site{% endblock %}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!--jquery and popper-->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<!--bootstrap css-->
<!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!--bootstrap js-->
<script src="{% static "bootstrap/js/bootstrap.min.js" %}" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!--bootstrap-toggle-->
<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>

<!--fontawesome-->
<!--<script src="https://kit.fontawesome.com/5fcc70e993.js" crossorigin="anonymous"></script>-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<link href="{% static "fontawesome/css/all.css" %}" rel="stylesheet">

<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>

{% block misc %}
{% endblock %}

<script>
$(document).ready(function() {
// get current URL path and assign 'active' class
	var id = {% block navtab %} "anno" {% endblock %};
	$("#" + id).addClass('active');
})
</script>

<style>
.fa-icon {
color: #eeeeee;
margin-right: 10px;
font-size:17px;
}

html, body {
	height: 100%;
}

body {
	display: flex;
	flex-direction: column;
}

.container-fluid#main {
	flex: 1 0 auto;
}

footer {
  width: 100%;
  background: #222;
  color: #eee;
  flex-shrink: 0;
  text-align: center;
}

</style>

</head>


<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
	<a class="navbar-brand" href="#">COIN<sup>2</sup></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
		  <a class="nav-link" href="/humantest/start" id="qa">QA <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="/admin" id="admin">Admin</a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="/humantest/stat" id="stat">Stat</a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="/humantest/help" id="help">Help</a>
      </li>
      <li class="nav-item">
		  <a class="nav-link" href="/accounts/logout" id="stat">Logout</a>
      </li>
    </ul>
  </div>
</nav>

{% block content %}
{% endblock %}

<!-- Footer -->
<!--<footer class="footer font-small py-3">-->

	<!--<div class="container-fluid text-center">-->
		<!--<div class="row">-->
			<!--<div class="col-sm-3">-->
					<!--<i class="fa fa-phone-alt fa-icon" aria-hidden="true"></i><a href="tel:13051108800">13051108800</a>-->
			<!--</div>-->
			<!--<div class="col-sm-6">-->
				<!--Copyright &copy; 2019 <a href="http://ivg.au.tsinghua.edu.cn" target="_blank" style="margin-left: 10px">Tsinghua i-VisionGroup</a>-->
			<!--</div>-->
			<!--<div class="col-sm-3">-->
					<!--<i class="fa fa-envelope-square fa-icon" aria-hidden="true"></i><a href="mailto:zhaowl16@mails.tsinghua.edu.cn?subject=Email Subject line">Email Us</a>-->
			<!--</div>-->
		<!--</div>-->
	<!--</div>-->
<!--</footer>-->
</body>
</html>

anno_tool/humantest/templates/humantest/help.html
{% extends "humantest/base.html" %}
{% load static %}
{% block title %}
COIN COIN Humantest
{% endblock %}

{% block misc %}
<style>
  .container-fluid#main {
  margin-top: 10%;
  padding-left:20%;
  padding-right:20%;
  line-height: 30px;
}

.light{
    -webkit-text-stroke: 1.5px white;
}

</style>
{% endblock %}

{% block navtab %}
	"help"
{% endblock %}

{% block content %}

<div class="container-fluid bg-1 text-center" id="main">

<h2 class="m-4"> COIN <sup>2</sup> Humantest </h2>

<h2 class="m-4"> 任务 </h2>
<ul class="text-left">
	<li>问题中的两张图片分别表示一个完整任务的开始和结束</li>
	<li>选项中的视频分别为中间可能出现的动作</li>
	<li>请选出你认为最合理的选项</li>
</ul>


<h2 class="m-4"> 快捷键 </h2>
<p class="text-justify">
可以使用键盘快捷键加速标注：
<table class="table">
	<thead>
	<tr><th>键盘</th><th>操作</th></tr>
	</thead>
	<tbody>
	<tr><td>A</td><td>选中选项A</td></tr>
	<tr><td>B</td><td>选中选项B</td></tr>
	<tr><td>C</td><td>选中选项C</td></tr>
	<tr><td>D</td><td>选中选项D</td></tr>
	<tr><td>Enter</td><td>提交选项</td></tr>
	</tbody>
</table>
</p>
</div>
{% endblock %}

anno_tool/humantest/templates/humantest/qa.html
{% extends "humantest/base.html" %}
{% load static %}

{% block title %}
  COIN COIN Humantest
{% endblock %}

{% block misc %}

<script>
$(window).keydown(function(e) {
  switch (e.keyCode) {
    case 13: // enter
		  if ($("#pid").is(":focus")) {
			  var new_pid = $("#pid").val();
			  if ("{{id}}"!= new_pid)
				  window.location.replace("/humantest/" + $("#pid").val());
		  }
		  else
			  $('#submit').click();
      return false;
    case 65:
		  $('#c0').click();
      return false;
    case 66:
		  $('#c1').click();
      return false;
    case 67:
		  $('#c2').click();
      return false;
    case 68:
		  $('#c3').click();
      return false;
    default:
      break;
      return false;
  }
});
</script>

<style type="text/css" media="screen">
.question {
	width: 30%;
}

.choices {
	width: 200px;
}


#main {
	margin-top: 80px;
	padding-left: 5%;
	padding-right: 5%;
}

.btn-group {
	margin-right: 5%;
	padding: 5px;
}

#pid {
  width: 80px;
  text-align: center;
}

.fa-arrows {
  color: #aaa;
  height: 100%;
  width: 1rem;
}

.fa-arrows:hover {
  color: #222;
}

input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance:textfield;
}

/* Bootstrap Toggle v2.2.2 corrections for Bootsrtap 4*/
.toggle-off {
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, .125);
}
.toggle.off {
  border-color: rgba(0, 0, 0, .25);
}

.toggle-handle {
  background-color: white;
  border: thin rgba(0, 0, 0, .25) solid;
}
</style>
{% endblock %}

{% block navtab %}
  "qa"
{% endblock %}

{% block content %}
  <div class="container-fluid bg-1" id="main">
	  <div class="row">
		  <div class="col-sm-3">
			<h4>Problem id<br/>
			  <div class="vid-group">
				<a href="{% url 'humantest:qa' id|add:"-1"%}" id="prev_vid">
				  <span class="fas fa-caret-left fa-arrows"></span>
				</a>
				<small>
				  <input type="number" value="{{id}}" name="" id="pid" min="1" max="{{ num_problems }}"/>
				</small>
				<a href="{% url 'humantest:qa' id|add:"1"%}" id="next_vid">
				  <span class="fas fa-caret-right fa-arrows"></span>
				</a>
			  </div>
			</h4>
		  </div>
		 <div class="col-sm-6">
		  {% for q in question %}
			  {% with 'data/'|add:q as static_q%}
				  <img src="{% static static_q %}" class="img-fluid question">
			  {% endwith %}
		  {%endfor%}
		</div>
		<div class="col-sm-3">
		  <div class="btn-group">
			<button type="button" class="btn btn-info dropdown-toggle btn-edit disable" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				{{setting}}
			</button>
			  <div class="dropdown-menu">
				  {% for setting in settings %}
					  <a class="dropdown-item" href="{% url "humantest:start" setting phase %}">{{setting}}</a>
				{% endfor %}
			  </div>
		  </div>
		  <div class="btn-group">
			<button type="button" class="btn btn-info dropdown-toggle btn-edit disable" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				{{phase}}
			</button>
			  <div class="dropdown-menu">
				<a class="dropdown-item disabled" href="{% url "humantest:start" setting "train" %}">train</a>
				<a class="dropdown-item" href="{% url "humantest:start" setting "test" %}">test</a>
			  </div>
		  </div>
		</div>
	  </div>
    <div class="progress m-3">
      <div class="progress-bar" role="progressbar" style="width: {{ratio_finished}}%;" aria-valuemin="0" aria-valuemax="100">{{num_finished}} / {{num_qas}}</div>
    </div>
	  <form action="{% url 'humantest:choose' id %}" method="post">
	  {% csrf_token %}
		  {% for c in choices %}
			  <div class="form-check">
				  <label class="form-check-label">
					  <input type="radio" class="form-check-input" name="answer" value={{ forloop.counter0 }} id="c{{ forloop.counter0 }}">
					  {% for s in c|get_item:"gifs" %}
						  {% with 'data/'|add:s as static_s%}
							  <img src="{% static static_s %}" class="img-fluid choices mx-2 my-1">
						  {% endwith %}
					  {% endfor %}
				  </label>
			  </div>

		  {% endfor %}

	  <button class="btn btn-success btn-edit" type="submit" name="submit" id="submit">Submit</button>
	  </div>

	  </form>
  </div>
{% endblock %}

anno_tool/humantest/templates/humantest/stat.html
{% extends "humantest/base.html" %}
{% load static %}

{% block title %}
  COIN COIN Annotation Tool
{% endblock %}

{% block misc %}
<style type="text/css" media="screen">
#main {
	margin-top: 80px;
	padding-left: 5%;
	padding-right: 5%;
}
</style>
{% endblock %}

{% block navtab %}
  "stat"
{% endblock %}

{% block content %}
<div class="container-fluid bg-1" id="main">
<h4>My Results</h4>
<table class="table">
	<thead>
		<tr><th>setting/phase</th><th>answered</th><th>correct</th><th>acc</th></tr>
	</thead>
	<tbody>
	{% for key, value in correct %}
    <tr>
        <td> {{ key }} </td> 
        <td> {{ num_answered|get_item:key }} </td>
        <td> {{ value }} </td>
        <td> {{ acc|get_item:key }} </td>
    </tr>
	</tbody>
{% endfor %}
</table>
</div>
{% endblock %}